### ISSUE TITLE
Can't get app to deploy

### ISSUE THREAD

**Issue by odrodrig** [IBM/manage-control-device-node-red#11]
When using the "Deploy to IBM Cloud" button the deploy stage fails with the following output:

<img width="913" alt="image" src="https://user-images.githubusercontent.com/12896721/44219950-e1064c80-a142-11e8-9959-c619a6945dc3.png">

The instructions to deploy from the terminal are also incomplete.

**Comment by hovig** [comment]
With the deployments to IBM Cloud being constant updates and changes, I have removed the command lines and modified the steps to make it easy on any user to be able to create this repo with no issues.
